### ISSUE TITLE
现在集群都用kubernetes了，希望能出个kubernetes部署的方案

### ISSUE THREAD

**Issue by we7team** [kofemann/pnfs-community#1]
现在集群都用kubernetes了，希望能出个kubernetes部署的方案

**Comment by kofemann** [comment]
:) if you write in English then I  probably can answer to your question.

**Comment by we7team** [comment]
Now that all clusters use kubernetes, we hope to have a solution for kubernetes deployment.

**Comment by kofemann** [comment]
See https://github.com/kofemann/pnfs-community-k8s
